A few fixes in netcgi2-apache. Including that into the release. Release 2.2.7
git-svn-id: https://godirepo.camlcity.org/svn/lib-ocamlnet2/trunk/code@1103 96e5b9e0-aa12-0410-9e2e-b23d24e56262

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -61,7 +61,7 @@ set_defaults () {
 ocamlc=`get_path ocamlc`
 set_defaults
 
-version="2.2.6"
+version="2.2.7"
 exec_suffix=""
 
 #######################################################################
@@ -71,7 +71,7 @@ ehelp_gtk="Enable/disable parts that depend on lablgtk"
 ehelp_gtk2="Enable/disable parts that depend on lablgtk2"
 ehelp_tcl="Enable/disable parts that depend on tcl/tk"
 ehelp_ssl="Enable/disable parts that depend on SSL"
-ehelp_apache="Enable/disable Apache mod connector"
+ehelp_apache="Enable/disable Apache mod connector (EXPERIMENTAL)"
 whelp_nethttpd="Enable/disable nethttpd web server component (GPL!)"
 whelp_rpc_auth_dh="Enable/disable support for SecureRPC (Diffie-Hellman auth)"
 
@@ -644,7 +644,7 @@ fi
 # Check Apache
 
 if [ $enable_apache -gt 0 ]; then
-    echo -n "Apache mod connector... "
+    printf "Apache mod connector... "
 
 #     echo "CURRENTLY BROKEN - disabling for now"
 #     enable_apache=0
@@ -675,8 +675,9 @@ if [ $enable_apache -gt 0 ]; then
     else
 	apache_major=
 	enable_apache=0
-	echo "disabled (apxs or apache not found)"
+	echo "apxs or apache not found"
 	echo "    Maybe you need to use the -apache option?"
+	exit 1
     fi
 
 fi
@@ -792,6 +793,7 @@ APACHE_LDFLAGS_SHLIB = $apache_ldflags_shlib
 APACHE_CC = $apache_cc
 APACHE_CFLAGS = $apache_cflags
 APACHE_OCAMLLIBDIR = $apache_ocamllibdir
+APXS = $apxs
 
 # Preferred CGI implementation
 PREFERRED_CGI_PKG=$preferred_cgi_pkg
